# Generated by Django 4.1.2 on 2023-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('patient_photo', models.ImageField(default='default_profile_pic.png', upload_to='profile_pics/')),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('visiting_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
